In [2]:
import numpy as np

#  1. insert the correct code for creating a numpy array

In [ ]:
a = np.array([1,2,3,4,5]) # use np
print(a) # [1 2 3 4 5]

[1 2 3 4 5]


#  2. consider this function:



In [ ]:
def what(n):
  a = np.array([1, 2, 3, 4], ndmin=n)
  print(a.ndim)
  return a

#     what is the difference between what(1), what(2) and what(3)

print(what(1)) # what do these print and why?
print(what(2))
print(what(3))


1
[1 2 3 4]
2
[[1 2 3 4]]
3
[[[1 2 3 4]]]


These print 1, 2, 3 respectively. The reason being that wen we call the what function and give the input n, we use that same input, n, in creating and declaring the minimum number of dimensions/axis in array a. So the dimensions of the array are n, thus the result of the what function will be the array declared, but based on the number it will be an array in an array in an array...


#  3. insert the correct argument for creating a numpy array with 2 dimensions

In [ ]:
a = np.array([[1, 2, 3, 4]])
print(a) # should print [[1 2 3 4]]

[[1 2 3 4]]


#  4. insert the correct syntax for checking the number of dimensions of a numpy array

In [ ]:
a = np.array([1, 2, 3, 4])
print(a.ndim ) # should print 1 (must refer to a)

b = np.array([[1, 2], [3, 4]])
print(b.ndim ) # should print 2 (must refer to b)

1
2


#  5. insert the correct syntax for printing the first item in the array:

In [ ]:
a = np.array([1, 2, 3, 4])
print(a[0] ) # should print 1 must use a

1


#  6. insert the correct syntax for printing the number 50 from the array

In [ ]:
a = np.array([10, 20, 30, 40, 50])
print(a[4]) # should print 50 must use a

50


#  7. insert the correct syntax for printing the number 50 from the array

In [ ]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(a[1][0]) # should print 50 must use a

50


#  8. use negative indexing to print the last item in the array

In [ ]:

a = np.array([10, 20, 30, 40, 50])
print(a[-1] ) # should print 50 must use a

50


#  9. slice out everything from the second item to (not including) the fifth item

In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[1:4]) # should print [15 20 25] must use a

[15 20 25]


# 10.slice out everything from the third item to (not including) the fifth item

In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[2:4]) # should print [20 25] must use a

[20 25]


# 11. slice out every other item from the second item to (not including) the fifth item

In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[1:4:2]) # should print [15 25] must use a

[15 25]


# 12. slice out every other item from the entire array

In [ ]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[::2]) # should print [10 20 30 40] must use a

[10 20 30 40]


# 13. insert correct syntax to print the datatype of an arra

In [ ]:
a = np.array([1, 2, 3])
print(a.dtype) # should print something indicating this is an array of integers
print(type(a[0])) # should print something indicating this is an array of integers

int64
<class 'numpy.int64'>


# 14. insert the correct argument to specify that array should be of type STRING

In [ ]:
a = np.array([1, 2, 3, 4], dtype= 'str' )

#     then predict and explain the output for the following expressions

print(a.dtype) #String/ str/  U5
print(a[0] + a[1]) #12
a = np.array([5, 1, -1, 3], dtype='str')
b = a.astype('i') # what happens here? Converts back to integer
print(b[0] + b[1] + b[3]) #9
print(a[0] + a[1] + a[3]) #Since still string it is 513

<U1
12
9
513


# 15. insert correct method to change data type to integer


In [ ]:
a = np.array([1.1, 2.1, 3.1])
b = a.astype('i')
print(b) # should print [1 2 3] now

[1 2 3]


# 16. use the correct method to make a copy of the array

In [ ]:
a = np.array([1, 2, 3, 4, 5])
x = a.copy()

#     then predict the effect of the following expressions

x[0] = -5
print(a) # does a see the change? No
b = a
b[0] = -25
print(a) # does a see the change? Yes


[1 2 3 4 5]
[1 2 3 4 5]
[-25   2   3   4   5]


# 17. use the correct method to make a view of this array:

In [6]:
a = np.array([1, 2, 3, 4, 5])
d = a.view()

#     then predict the effect of these expressions:

print(a.base)
print(d.base) # why is this different from all the others?
#The .view function works by assoiating another variable with the same array. So when you make changes to one variable that is associated to that array you make changes to all arrays. This means that the array itself is the base for the variable thus it is different.
b = a
print(b.base)
c = a.copy()
print(c.base)

None
[1 2 3 4 5]
None
None


# 18.predict (and explain) the outcome of these expressions

In [13]:
a = np.array([1, 2, 3, 4])
print(a.shape)# 4 because there are four items in the array.
a.reshape(1, 4)
print(a.reshape(1,4)) #1 array with 4 colums
a.reshape(2, 2) 
print(a.reshape(2,2)) #2 x 2
a.reshape(4, 1)
print(a.reshape(4,1)) #4 x 1


(4,)
[[1 2 3 4]]
[[1 2]
 [3 4]]
[[1]
 [2]
 [3]
 [4]]


 # 19. use the correct numpy method to change the shape of an array from 1-D to 2-D:

In [14]:
a = np.array([1, 2, 3, 4])
a = a.reshape(2,2) # write code here must use a
print(a) # must print [[1, 2] [3 4]]

[[1 2]
 [3 4]]


In [15]:
#     now predict and explain the output of these expressions 

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(4, 3) #Splits the single array into 4 different arrays 
print(b)
b = a.reshape(3, 4) #splits single a array into 3 arrays with a length of 4
print(b)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 20. use correct numpy method to change shape of an array from 2-D to 1-D

In [18]:
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
b = a.reshape(-1) # complete this statement to result in the output below
print(b) # must print [ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 21. use a correct numpy method to join two arrays into a single array

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.append(a,b) # use np, a and b somehow 
print(c) # must print [1 2 3 4 5 6]

#     then predict and explain the outcome of the following expressions

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=1) # what is the effect of the second parameter? 
print(c) # what gets printed and why? one array that is filled with numbers the numbers from the first array for the variable and a second array that is filled witht hte numbers from the second variable.
c  = np.stack((a, b), axis = 0) # what does stack do differently (if anything)? Stacking doesn't mesh the numbers together it just makes a new array where the inputs are elements of the new array/
print(c) # what gets printed and why? 


[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# 22. use correct numpy syntax to find all items with value 4

In [23]:
a = np.array([1, 2, 3, 4, 5, 4, 4])
where = np.where(a == 4,) # complete statement, must use np, a and 4
print(where) # must print (array([3, 5, 6]),)

(array([3, 5, 6]),)


# 23. use the correct numpy method to return a sorted array

In [25]:
a = np.array([3, 2, 0, 1])
b = np.sort(a) # complete statement, must use np and a
print(b) # must print [0 1 2 3] 

[0 1 2 3]


# 24. solve exercise 3-1 on page 57

Go back to the taxation example in “Basic Two-Dimensional Array Arithmetic” on page 42 and pull the name of the person with the highest salary from
the matrix by using this idea of selective Boolean indexing. Problem recap: How do we find the person with maximum after-tax income in a group of people, given their yearly salary and tax rates?


In [18]:

## Data: yearly salary in ($1000) [2017, 2018, 2019]
alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]
names = ["alice","bob","tim"]
salaries = np.array([alice, bob, tim])
taxation = np.array([[0.2, 0.25, 0.22],
                     [0.4, 0.5, 0.5],
                     [0.1, 0.2, 0.1]])
income = salaries -salaries*taxation
## One-liner
max_income = np.max(salaries - salaries * taxation)
## Result
print(max_income)

81.0


In [13]:
income

array([[79.2 , 75.75, 80.34],
       [66.  , 54.  , 52.5 ],
       [81.  , 70.4 , 76.5 ]])

In [19]:
print(np.argmax(income, axis = 1))
indexes = np.argmax(income, axis = 1)
for i in indexes:
  print(names[i])

[2 0 0]
tim
alice
alice


# 25. predict and explain the effect of the following expressions

In [5]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np.average(a, axis=0)) # Axis 0 looks at all the columns of the matrices and then the avg function averages them out.
print(np.average(a, axis=1)) # Axis 1 Looks at the numbers in the second dimension and then then add's them respectively. Ex. 1 + 3 /2
print(np.average(a, axis=2)) # Axis 2 Looks at the numbers in the first dimension and then averages them to get the final matrix.

[[3. 4.]
 [5. 6.]]
[[2. 3.]
 [6. 7.]]
[[1.5 3.5]
 [5.5 7.5]]


# 26. predict and explain the effect of the following expressions

In [9]:
a = np.array([[[ 1,  2,  3], [22,  5,  6], [ 7,  8,  9]],
              [[11, 12, 10], [ 4, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [13, 23, 24], [25, 26, 27]]])

b = np.sort(a, axis=0) # organizes the array column by column. Then Then the samlles number goes in the first depth array and so on...
print(b) # what gets printed and why? It organizes the array column by column this occurs as we are sorting by axis 0.
c = np.sort(a, axis=1) # Organizes each array by row so the smallest first number in the array comes first and that finishes the first of the 3 depth arrays and then this repeats.
print(c)
d = np.sort(a, axis=2) #The second dimension stay in the same position but since axis 2 is focused on depth it re-orders the nubers in the 1st dimenson array so then are in order.
print(d)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 10]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 7  5  6]
  [22  8  9]]

 [[ 4 12 10]
  [11 14 15]
  [16 17 18]]

 [[13 20 21]
  [19 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 5  6 22]
  [ 7  8  9]]

 [[10 11 12]
  [ 4 14 15]
  [16 17 18]]

 [[19 20 21]
  [13 23 24]
  [25 26 27]]]
